require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/api_logs", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ApiLog. As you add validations to ApiLog, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ApiLog.create! valid_attributes
      get api_logs_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      api_log = ApiLog.create! valid_attributes
      get api_log_url(api_log)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_api_log_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      api_log = ApiLog.create! valid_attributes
      get edit_api_log_url(api_log)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ApiLog" do
        expect {
          post api_logs_url, params: { api_log: valid_attributes }
        }.to change(ApiLog, :count).by(1)
      end

      it "redirects to the created api_log" do
        post api_logs_url, params: { api_log: valid_attributes }
        expect(response).to redirect_to(api_log_url(ApiLog.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ApiLog" do
        expect {
          post api_logs_url, params: { api_log: invalid_attributes }
        }.to change(ApiLog, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post api_logs_url, params: { api_log: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested api_log" do
        api_log = ApiLog.create! valid_attributes
        patch api_log_url(api_log), params: { api_log: new_attributes }
        api_log.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the api_log" do
        api_log = ApiLog.create! valid_attributes
        patch api_log_url(api_log), params: { api_log: new_attributes }
        api_log.reload
        expect(response).to redirect_to(api_log_url(api_log))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        api_log = ApiLog.create! valid_attributes
        patch api_log_url(api_log), params: { api_log: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested api_log" do
      api_log = ApiLog.create! valid_attributes
      expect {
        delete api_log_url(api_log)
      }.to change(ApiLog, :count).by(-1)
    end

    it "redirects to the api_logs list" do
      api_log = ApiLog.create! valid_attributes
      delete api_log_url(api_log)
      expect(response).to redirect_to(api_logs_url)
    end
  end
end
