require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/application_credentials", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ApplicationCredential. As you add validations to ApplicationCredential, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ApplicationCredential.create! valid_attributes
      get application_credentials_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      application_credential = ApplicationCredential.create! valid_attributes
      get application_credential_url(application_credential)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_application_credential_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      application_credential = ApplicationCredential.create! valid_attributes
      get edit_application_credential_url(application_credential)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ApplicationCredential" do
        expect {
          post application_credentials_url, params: { application_credential: valid_attributes }
        }.to change(ApplicationCredential, :count).by(1)
      end

      it "redirects to the created application_credential" do
        post application_credentials_url, params: { application_credential: valid_attributes }
        expect(response).to redirect_to(application_credential_url(ApplicationCredential.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ApplicationCredential" do
        expect {
          post application_credentials_url, params: { application_credential: invalid_attributes }
        }.to change(ApplicationCredential, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post application_credentials_url, params: { application_credential: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested application_credential" do
        application_credential = ApplicationCredential.create! valid_attributes
        patch application_credential_url(application_credential), params: { application_credential: new_attributes }
        application_credential.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the application_credential" do
        application_credential = ApplicationCredential.create! valid_attributes
        patch application_credential_url(application_credential), params: { application_credential: new_attributes }
        application_credential.reload
        expect(response).to redirect_to(application_credential_url(application_credential))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        application_credential = ApplicationCredential.create! valid_attributes
        patch application_credential_url(application_credential), params: { application_credential: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested application_credential" do
      application_credential = ApplicationCredential.create! valid_attributes
      expect {
        delete application_credential_url(application_credential)
      }.to change(ApplicationCredential, :count).by(-1)
    end

    it "redirects to the application_credentials list" do
      application_credential = ApplicationCredential.create! valid_attributes
      delete application_credential_url(application_credential)
      expect(response).to redirect_to(application_credentials_url)
    end
  end
end
