require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/application_doc_requests", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ApplicationDocRequest. As you add validations to ApplicationDocRequest, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ApplicationDocRequest.create! valid_attributes
      get application_doc_requests_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      application_doc_request = ApplicationDocRequest.create! valid_attributes
      get application_doc_request_url(application_doc_request)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_application_doc_request_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      application_doc_request = ApplicationDocRequest.create! valid_attributes
      get edit_application_doc_request_url(application_doc_request)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ApplicationDocRequest" do
        expect {
          post application_doc_requests_url, params: { application_doc_request: valid_attributes }
        }.to change(ApplicationDocRequest, :count).by(1)
      end

      it "redirects to the created application_doc_request" do
        post application_doc_requests_url, params: { application_doc_request: valid_attributes }
        expect(response).to redirect_to(application_doc_request_url(ApplicationDocRequest.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ApplicationDocRequest" do
        expect {
          post application_doc_requests_url, params: { application_doc_request: invalid_attributes }
        }.to change(ApplicationDocRequest, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post application_doc_requests_url, params: { application_doc_request: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested application_doc_request" do
        application_doc_request = ApplicationDocRequest.create! valid_attributes
        patch application_doc_request_url(application_doc_request), params: { application_doc_request: new_attributes }
        application_doc_request.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the application_doc_request" do
        application_doc_request = ApplicationDocRequest.create! valid_attributes
        patch application_doc_request_url(application_doc_request), params: { application_doc_request: new_attributes }
        application_doc_request.reload
        expect(response).to redirect_to(application_doc_request_url(application_doc_request))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        application_doc_request = ApplicationDocRequest.create! valid_attributes
        patch application_doc_request_url(application_doc_request), params: { application_doc_request: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested application_doc_request" do
      application_doc_request = ApplicationDocRequest.create! valid_attributes
      expect {
        delete application_doc_request_url(application_doc_request)
      }.to change(ApplicationDocRequest, :count).by(-1)
    end

    it "redirects to the application_doc_requests list" do
      application_doc_request = ApplicationDocRequest.create! valid_attributes
      delete application_doc_request_url(application_doc_request)
      expect(response).to redirect_to(application_doc_requests_url)
    end
  end
end
