require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/application_credential_proxy_logs", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ApplicationCredentialProxyLog. As you add validations to ApplicationCredentialProxyLog, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ApplicationCredentialProxyLog.create! valid_attributes
      get application_credential_proxy_logs_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      application_credential_proxy_log = ApplicationCredentialProxyLog.create! valid_attributes
      get application_credential_proxy_log_url(application_credential_proxy_log)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_application_credential_proxy_log_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      application_credential_proxy_log = ApplicationCredentialProxyLog.create! valid_attributes
      get edit_application_credential_proxy_log_url(application_credential_proxy_log)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ApplicationCredentialProxyLog" do
        expect {
          post application_credential_proxy_logs_url, params: { application_credential_proxy_log: valid_attributes }
        }.to change(ApplicationCredentialProxyLog, :count).by(1)
      end

      it "redirects to the created application_credential_proxy_log" do
        post application_credential_proxy_logs_url, params: { application_credential_proxy_log: valid_attributes }
        expect(response).to redirect_to(application_credential_proxy_log_url(ApplicationCredentialProxyLog.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ApplicationCredentialProxyLog" do
        expect {
          post application_credential_proxy_logs_url, params: { application_credential_proxy_log: invalid_attributes }
        }.to change(ApplicationCredentialProxyLog, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post application_credential_proxy_logs_url, params: { application_credential_proxy_log: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested application_credential_proxy_log" do
        application_credential_proxy_log = ApplicationCredentialProxyLog.create! valid_attributes
        patch application_credential_proxy_log_url(application_credential_proxy_log), params: { application_credential_proxy_log: new_attributes }
        application_credential_proxy_log.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the application_credential_proxy_log" do
        application_credential_proxy_log = ApplicationCredentialProxyLog.create! valid_attributes
        patch application_credential_proxy_log_url(application_credential_proxy_log), params: { application_credential_proxy_log: new_attributes }
        application_credential_proxy_log.reload
        expect(response).to redirect_to(application_credential_proxy_log_url(application_credential_proxy_log))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        application_credential_proxy_log = ApplicationCredentialProxyLog.create! valid_attributes
        patch application_credential_proxy_log_url(application_credential_proxy_log), params: { application_credential_proxy_log: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested application_credential_proxy_log" do
      application_credential_proxy_log = ApplicationCredentialProxyLog.create! valid_attributes
      expect {
        delete application_credential_proxy_log_url(application_credential_proxy_log)
      }.to change(ApplicationCredentialProxyLog, :count).by(-1)
    end

    it "redirects to the application_credential_proxy_logs list" do
      application_credential_proxy_log = ApplicationCredentialProxyLog.create! valid_attributes
      delete application_credential_proxy_log_url(application_credential_proxy_log)
      expect(response).to redirect_to(application_credential_proxy_logs_url)
    end
  end
end
