require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/db_scrappers", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # DbScrapper. As you add validations to DbScrapper, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      DbScrapper.create! valid_attributes
      get db_scrappers_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      db_scrapper = DbScrapper.create! valid_attributes
      get db_scrapper_url(db_scrapper)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_db_scrapper_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      db_scrapper = DbScrapper.create! valid_attributes
      get edit_db_scrapper_url(db_scrapper)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new DbScrapper" do
        expect {
          post db_scrappers_url, params: { db_scrapper: valid_attributes }
        }.to change(DbScrapper, :count).by(1)
      end

      it "redirects to the created db_scrapper" do
        post db_scrappers_url, params: { db_scrapper: valid_attributes }
        expect(response).to redirect_to(db_scrapper_url(DbScrapper.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new DbScrapper" do
        expect {
          post db_scrappers_url, params: { db_scrapper: invalid_attributes }
        }.to change(DbScrapper, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post db_scrappers_url, params: { db_scrapper: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested db_scrapper" do
        db_scrapper = DbScrapper.create! valid_attributes
        patch db_scrapper_url(db_scrapper), params: { db_scrapper: new_attributes }
        db_scrapper.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the db_scrapper" do
        db_scrapper = DbScrapper.create! valid_attributes
        patch db_scrapper_url(db_scrapper), params: { db_scrapper: new_attributes }
        db_scrapper.reload
        expect(response).to redirect_to(db_scrapper_url(db_scrapper))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        db_scrapper = DbScrapper.create! valid_attributes
        patch db_scrapper_url(db_scrapper), params: { db_scrapper: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested db_scrapper" do
      db_scrapper = DbScrapper.create! valid_attributes
      expect {
        delete db_scrapper_url(db_scrapper)
      }.to change(DbScrapper, :count).by(-1)
    end

    it "redirects to the db_scrappers list" do
      db_scrapper = DbScrapper.create! valid_attributes
      delete db_scrapper_url(db_scrapper)
      expect(response).to redirect_to(db_scrappers_url)
    end
  end
end
