require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/knowledge_queryfiers", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # KnowledgeQueryfier. As you add validations to KnowledgeQueryfier, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      KnowledgeQueryfier.create! valid_attributes
      get knowledge_queryfiers_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      knowledge_queryfier = KnowledgeQueryfier.create! valid_attributes
      get knowledge_queryfier_url(knowledge_queryfier)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_knowledge_queryfier_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      knowledge_queryfier = KnowledgeQueryfier.create! valid_attributes
      get edit_knowledge_queryfier_url(knowledge_queryfier)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new KnowledgeQueryfier" do
        expect {
          post knowledge_queryfiers_url, params: { knowledge_queryfier: valid_attributes }
        }.to change(KnowledgeQueryfier, :count).by(1)
      end

      it "redirects to the created knowledge_queryfier" do
        post knowledge_queryfiers_url, params: { knowledge_queryfier: valid_attributes }
        expect(response).to redirect_to(knowledge_queryfier_url(KnowledgeQueryfier.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new KnowledgeQueryfier" do
        expect {
          post knowledge_queryfiers_url, params: { knowledge_queryfier: invalid_attributes }
        }.to change(KnowledgeQueryfier, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post knowledge_queryfiers_url, params: { knowledge_queryfier: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested knowledge_queryfier" do
        knowledge_queryfier = KnowledgeQueryfier.create! valid_attributes
        patch knowledge_queryfier_url(knowledge_queryfier), params: { knowledge_queryfier: new_attributes }
        knowledge_queryfier.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the knowledge_queryfier" do
        knowledge_queryfier = KnowledgeQueryfier.create! valid_attributes
        patch knowledge_queryfier_url(knowledge_queryfier), params: { knowledge_queryfier: new_attributes }
        knowledge_queryfier.reload
        expect(response).to redirect_to(knowledge_queryfier_url(knowledge_queryfier))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        knowledge_queryfier = KnowledgeQueryfier.create! valid_attributes
        patch knowledge_queryfier_url(knowledge_queryfier), params: { knowledge_queryfier: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested knowledge_queryfier" do
      knowledge_queryfier = KnowledgeQueryfier.create! valid_attributes
      expect {
        delete knowledge_queryfier_url(knowledge_queryfier)
      }.to change(KnowledgeQueryfier, :count).by(-1)
    end

    it "redirects to the knowledge_queryfiers list" do
      knowledge_queryfier = KnowledgeQueryfier.create! valid_attributes
      delete knowledge_queryfier_url(knowledge_queryfier)
      expect(response).to redirect_to(knowledge_queryfiers_url)
    end
  end
end
